// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAMftlZKjXS0vnyG7vWj_SehvDLFaitB8',
    appId: '1:497546432522:web:0249428eccc46930cf8ff3',
    messagingSenderId: '497546432522',
    projectId: 'eidclean',
    authDomain: 'eidclean.firebaseapp.com',
    storageBucket: 'eidclean.firebasestorage.app',
    measurementId: 'G-WQ4G3H1B7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUujYgl_OdcZzEGkG9TsGjtrMhbvnSM08',
    appId: '1:497546432522:android:3086d40248235ccbcf8ff3',
    messagingSenderId: '497546432522',
    projectId: 'eidclean',
    storageBucket: 'eidclean.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzYyw3pB9lsMXcrxPSocTf7j-FBNaLoms',
    appId: '1:497546432522:ios:1d82d98245466f5bcf8ff3',
    messagingSenderId: '497546432522',
    projectId: 'eidclean',
    storageBucket: 'eidclean.firebasestorage.app',
    iosBundleId: 'com.example.eidcleanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzYyw3pB9lsMXcrxPSocTf7j-FBNaLoms',
    appId: '1:497546432522:ios:1d82d98245466f5bcf8ff3',
    messagingSenderId: '497546432522',
    projectId: 'eidclean',
    storageBucket: 'eidclean.firebasestorage.app',
    iosBundleId: 'com.example.eidcleanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAMftlZKjXS0vnyG7vWj_SehvDLFaitB8',
    appId: '1:497546432522:web:c307b5adb7deb773cf8ff3',
    messagingSenderId: '497546432522',
    projectId: 'eidclean',
    authDomain: 'eidclean.firebaseapp.com',
    storageBucket: 'eidclean.firebasestorage.app',
    measurementId: 'G-Y1R0N3VCFD',
  );
}
